// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Puppet.Service;
using Puppet;


[PrefabAttribute(Name = "Prefabs/Dialog/DialogInbox", Depth = 7, IsAttachedToCamera = true, IsUIPanel = true)]
public class DialogInboxView : BaseDialog<DialogInbox,DialogInboxView>
{
	#region UnityEditor
	public UIToggle rdbSystemMessage,rdbFriendMessage,rdbNews;
	public UITable tblContent;
	protected override void OnEnable ()
	{
		base.OnEnable ();
		EventDelegate.Add (rdbSystemMessage.onChange, OnSelectSystemMsg);
		EventDelegate.Add (rdbFriendMessage.onChange, OnSelectFriendMsg);
		EventDelegate.Add (rdbNews.onChange, OnSelectNews);
	}
	protected override void OnDisable ()
	{
		base.OnDisable ();
		EventDelegate.Remove (rdbSystemMessage.onChange, OnSelectSystemMsg);
		EventDelegate.Remove (rdbFriendMessage.onChange, OnSelectFriendMsg);
		EventDelegate.Remove (rdbNews.onChange, OnSelectNews);
	}
	private void OnSelectSystemMsg (){
		Logger.Log ("========>  click to tab System Message" );
	}
	private void OnSelectFriendMsg (){
		Logger.Log ("========>  click to tab Friend Message" );
	}
	private void OnSelectNews (){
		Logger.Log ("========>  click to tab News Message" );
	}
	#endregion
	public override void ShowDialog (DialogInbox data)
	{
		base.ShowDialog (data);
	}
}
public class DialogInbox : AbstractDialogData{

	public DialogInbox():base(){

	}
	public override void ShowDialog ()
	{
		DialogInboxView.Instance.ShowDialog (this);
	}
}


