// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Puppet.Service;
using System.Collections.Generic;
using UnityEngine;
using Puppet.Core.Model;
using Puppet;
namespace Puppet.Service{
[PrefabAttribute(Name = "Prefabs/Dialog/Friend/DialogListFriend", Depth = 7, IsAttachedToCamera = true, IsUIPanel = true)]
public class DialogListFriendView : BaseDialog<DialogListFriend,DialogListFriendView>
{
		#region 
		public UITable tableListFriend;
		public UITexture avatar;
		public UILabel lbUserName,lbChips,lbLevel,lbNumberPlayed,lbWinPercents;
		public GameObject btnChipGift,btnItemGift,btnJoinGame;
		#endregion
		public override void ShowDialog (DialogListFriend data)
		{
			base.ShowDialog (data);

		}
		protected override void OnEnable(){
		
			UIEventListener.Get (btnChipGift).onClick += onSendChip;
			UIEventListener.Get (btnItemGift).onClick += onSendItem;
			UIEventListener.Get (btnJoinGame).onClick += onJoinGame;
			base.OnEnable ();
		}
		protected override void OnDisable(){

			UIEventListener.Get (btnChipGift).onClick -= onSendChip;
			UIEventListener.Get (btnItemGift).onClick -= onSendItem;
			UIEventListener.Get (btnJoinGame).onClick -= onJoinGame;
			base.OnDisable ();
		}

		void onSendChip (GameObject go)
		{
		}

		void onSendItem (GameObject go)
		{

		}

		void onJoinGame (GameObject go)
		{

		}
	}
	public class DialogListFriend : AbstractDialogData{
		public List<UserInfo> users;
		public DialogListFriend(List<UserInfo> users) : base(){
			this.users = users;
		}
		public override void ShowDialog ()
		{
			DialogListFriendView.Instance.ShowDialog (this);
		}
	}
}

