// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Puppet.Service;
using Puppet;
using UnityEngine;

[PrefabAttribute(Name = "Prefabs/Dialog/DialogLoading", Depth = 99, IsAttachedToCamera = true, IsUIPanel = true)]
public class LoadingView : SingletonPrefab<LoadingView>
{
	#region UnityEditor
	public UISprite transparentLeft, transparentRight;
	public UI2DSprite loadingIcon;
	public bool isClose = false;
	int width ;
	int height;
	#endregion
	void Start(){
//		CalculatorTwoBackground ();
	}

	public void CalculatorTwoBackground(){
		UIRoot mRoot = NGUITools.FindInParents<UIRoot>(gameObject);
		
		float ratio = (float)mRoot.activeHeight / Screen.height;
		
		width = Mathf.CeilToInt(Screen.width * ratio);
		height = Mathf.CeilToInt(Screen.height * ratio);
		
		
		transparentLeft.width = transparentRight.width = (int)width / 2;
		transparentLeft.height = transparentRight.height = (int)height;

		transparentLeft.transform.localPosition = new UnityEngine.Vector3(-width/1.3f,0f,0f);
		transparentRight.transform.localPosition = new UnityEngine.Vector3(width/1.3f,0f,0f);
		StartTranslate ();
	}
	public void Show(){
		CalculatorTwoBackground ();
	}
	private void StartTranslate(){
		iTween.MoveTo(transparentLeft.gameObject,iTween.Hash("islocal", true,"time",.8,"position",new Vector3(-width/4f,0f,0f),"easetype", iTween.EaseType.easeInOutExpo,"oncomplete","CompleteSlideInto","oncompletetarget",gameObject)); 
		iTween.MoveTo(transparentRight.gameObject,iTween.Hash("islocal", true,"time",.8,"position",new Vector3(width/4f,0f,0f),"easetype", iTween.EaseType.easeInOutExpo,"oncomplete","CompleteSlideInto","oncompletetarget",gameObject));
	}
	private void CompleteSlideInto(){
		loadingIcon.gameObject.SetActive (true);
	}
	public void Close(){
		loadingIcon.gameObject.SetActive (false);
		iTween.MoveTo(transparentLeft.transform.parent.gameObject,iTween.Hash("islocal", true,"time",.8,"position",new Vector3(0f,height,0f),"easetype", iTween.EaseType.easeInOutExpo,"oncomplete","OnClose","oncompletetarget",gameObject)); 
	}

	private void OnClose(){
		GameObject.Destroy (gameObject);
	}
	void Update(){
		if (isClose)
			Close ();
	}
}


