// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Puppet.Service
{
	[PrefabAttribute(Name = "Prefabs/Dialog/DialogPromotion", Depth = 10, IsAttachedToCamera = true, IsUIPanel = true)]
	public class DialogPromotionView :BaseDialog<DialogPromotion, DialogPromotionView>
	{

	}
}


