// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class PromotionPresenter : IPromotionPresenter
{
	IPromotionView view;

	public int index;

	public IPromotionView View {
		get {
			return view;
		}
		set{
			this.view = value;
		}
	}
	Action action;
	#region IPresenter implementation

	public PromotionPresenter(string day,string money,string shortcut,int index,Action action)
	{
		this.index = index;
		PromotionView.newInstance (this);
		view.ShowInfo (day, money, shortcut);
		this.action = action;
	}
	public void GetPromotion ()
	{
		if (action != null)
			action ();
	}


	#endregion


}


