// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Puppet;

public interface ILoginPresenter : IPresenter
{
	void LoginWithUserName(string username,string password);
	void LoginWithAccessToken(string accessToken);
	void LoginFacebook();
	void GetAccessTokenWithSocial(string accessToken);
	void LoginTrail();
    void ShowRegister();
}


